### ISSUE TITLE
Error when trying to import gausspy

### ISSUE THREAD

**Issue by cosmicpudding** [gausspy/gausspy#15]
I've just tried to follow the instructions and install gausspy, but I get an "illegal instruction" error:

> In [1]: import gausspy.gp as gp
> Illegal instruction: 4

This was after both using `2to3 -w *py` to change everything to Python 3 compatible, and also just manually fixing the print statements. Not sure what is causing this, any help would be much appreciated!

**Comment by cmurray-astro** [comment]
@cosmicpudding apologies for the delay in replying to this! We are working on updating the code to support Python 3 ASAP. Any chance that you are still receiving this error?

**Comment by cmurray-astro** [comment]
closing
