### ISSUE TITLE
Workflow recommendation

### ISSUE THREAD

**Issue by keflavich** [gausspy/gausspy#2]
I tried following the tutorial and found the workflow to be fairly counterintuitive, but I found a reasonable option that might serve as a better 'getting started' example:

```
import gausspy.gp as gp
gg=gp.GaussianDecomposer()
gg.p['alpha1'] = 0.5
gg.p['SNR_thresh'] = [5,5]
spectral_data = #(generate spectral data here, that's not the point of this example)
spectral_axis = xaxis
spectral_error = err

result = gg.decompose(spectral_axis, spectral_data, spectral_error)

individual_models = [gaussian(result['best_fit_parameters'][ii], result['best_fit_parameters'][ii+result['N_components']], result['best_fit_parameters'][ii+result['N_components']*2])(spectral_axis) for ii in range(result['N_components'])]
composite_model = np.sum(individual_models, axis=0)

import pylab as pl
pl.plot(spectral_axis, spectral_data)
pl.plot(spectral_axis, composite_model)
```

Can you see anything wrong with this example, for starters? (i.e., did I miss anything important?)  Do you have any preferred way to parse the results into models?

**Comment by cmurray-astro** [comment]
Hello,
First off, apologies for the very slow reply. Thank you for submitting the above suggestion, which looks good, and highlights the two free parameters in the decomposition, namely alpha ('alpha1') and the signal to noise ratio threshold (`SNR_thresh'). This is a nice example for getting started before delving into training the algorithm. I am currently updating the documentation to include a similar "getting started" example. 

As for parsing the results into models, there is not currently a preferred method, although a variation of the above example is what is typically used. Is there a particular application or format that you are interested in? 

Thanks again!

**Comment by yaseminpoyraz** [comment]
Hello,
I want to write an script to use the gausspy. I am using test_examples.py file. I add main() module to call test_train() module. In this module gausspy.gp imported like this 'import gausspy.gp as gp'. But I am getting "ImportError: No module named gausspy.gp" error message. How can i import this file. I installed gausspy package.

**Comment by cmurray-astro** [comment]
Hello, it sounds like the problem concerns where you installed the gausspy package, and whether this location is included in your PYTHONPATH environment variable. Have you verified this?

**Comment by yaseminpoyraz** [comment]
Hello,
I installed the gausspy package on my home directory. How can i
include PYTHONPATH
environment variable?

2018-02-21 19:16 GMT+01:00 cemurray3 <notifications@github.com>:

**Comment by cmurray-astro** [comment]
This is not a problem related to gausspy, however the following may be useful:
https://docs.python.org/2/tutorial/modules.html#the-module-search-path

You can set your PYTHONPATH environment variable, for example in your .tcshrc file:
setenv PYTHONPATH path

or in your .bashrc file:

PYTHONPATH=”path”
export ${PYTHONPATH}

where instead of "path", you include the directory where gausspy (or other Python modules) are installed.
