### ISSUE TITLE
Multiple decompose runs give same results

### ISSUE THREAD

**Issue by jd-au** [gausspy/gausspy#3]
When running decomposition in a loop only the results of the first decomposition (data in the first pickle file) gets written into all output files.

For example:

```
g = gp.GaussianDecomposer()
g.set('mode','conv')
g.set('phase', 'one')
g.set('SNR_thresh', [5, 5])
g.set('alpha1', 4)
decomposed_dat_a4 = g.batch_decomposition(data_filename)
g = gp.GaussianDecomposer()
g.set('mode','conv')
g.set('phase', 'one')
g.set('SNR_thresh', [5, 5])
g.set('alpha1', 6)
decomposed_data_a6 = g.batch_decomposition(data_filename)
```

Both decomposed_data_a4 and decomposed_data_a6 will contain the same results despite the use of different alpha values. If the two runs are in different python invocations the results differ as expected.

**Comment by jd-au** [comment]
Pull request https://github.com/gausspy/gausspy/pull/4 submitted to fix this issue

**Comment by gausspy** [comment]
Request merged. Thanks!
